version: "3.8"

services:
  mysql_db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "PIdb"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    build: .
    depends_on:
      - mysql_db
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:3306/PIdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.servlet.context-path": "/pi",
        "server.port": "8089"
      }'
    volumes:
      - .m2:/root/.m2
      - .:/workdir/server/src
      - ./src/main/resources/application.yml:/workdir/server/src/main/resources/application.yml
    stdin_open: true
    tty: true

  frontend:
    image: achillesxv/frontendpi
    restart: always
    ports:
      - "80:80"

volumes:
  db: